name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # This triggers the action when pushing to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
          
      - name: Build the app
        run: deno task build # Change this if you have a specific build script

      - name: Copy index.html to the dist folder
        run: cp index.html dist/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist  # Assuming your build outputs to the dist folder
